import * as T from './vendor/three.module.js';
import {HDRLoader} from './vendor/HDRLoader.js';
const asset=url=>new URL(url,import.meta.url).href;
export async function createEngine(report){
 const renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.outputColorSpace=T.SRGBColorSpace;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(45,1,.1,30);camera.position.set(0,0,5);const group=new T.Group();scene.add(group);
 const key=new T.DirectionalLight(0xffffff,3);key.position.set(2,3,3);scene.add(key);const fill=new T.HemisphereLight(0xffffff,0x202020,.35);scene.add(fill);
 const overlay={value:0};function ceramic(options){const m=new T.MeshStandardMaterial({...options,side:T.DoubleSide});m.onBeforeCompile=shader=>{shader.uniforms.overlayAmount=overlay;shader.vertexShader='attribute float cavity; varying float vCavity;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvCavity=cavity;');shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>', 'float roughnessFactor = roughness;\n#ifdef USE_ROUGHNESSMAP\nroughnessFactor *= mix(0.7,1.15,texture2D(roughnessMap,vRoughnessMapUv).g);\n#endif');shader.fragmentShader='varying float vCavity; uniform float overlayAmount;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <opaque_fragment>','outgoingLight *= mix(0.5,1.0,vCavity);\nfloat rim=pow(1.0-max(dot(normalize(normal),normalize(vViewPosition)),0.0),3.0);\noutgoingLight=mix(outgoingLight,vec3(0.012)+outgoingLight*0.035+vec3(rim*1.4),overlayAmount);\n#include <opaque_fragment>');};return m}
 const outer=ceramic({color:0xece9e2,roughness:.8,metalness:0}),inner=ceramic({color:0xfffaf0,roughness:.3,metalness:0});
 let meshes=[],textures=[],environment='',loadingEnv='',loadId=0;const envCache=new Map(),pmrem=new T.PMREMGenerator(renderer);pmrem.compileEquirectangularShader();
 const loader=new T.TextureLoader();await Promise.all(['basecolor','normal','roughness'].map(async name=>{const tex=await loader.loadAsync(asset('./assets/tex_forma_'+name+'.png'));tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(name==='basecolor')tex.colorSpace=T.SRGBColorSpace;textures.push(tex);outer[name==='basecolor'?'map':name==='normal'?'normalMap':'roughnessMap']=tex;}));outer.needsUpdate=true;
 async function setEnvironment(name){const id=++loadId;loadingEnv=name;report('Loading '+name+' HDRI…');try{if(!envCache.has(name)){const hdr=await new HDRLoader().loadAsync(asset('./assets/tex_forma_'+name+'.hdr'));const target=pmrem.fromEquirectangular(hdr);hdr.dispose();envCache.set(name,target)}if(id!==loadId)return;scene.environment=envCache.get(name).texture;environment=name;loadingEnv='';report(name==='studio'?'Studio HDRI ready':'Metal studio HDRI ready')}catch(e){if(id===loadId){loadingEnv='';report('HDRI failed: '+e.message)}}}
 function geometry(data){for(let i=0;i<data.length;i+=24){let u=[data[i+8]-data[i],data[i+9]-data[i+1],data[i+10]-data[i+2]],v=[data[i+16]-data[i],data[i+17]-data[i+1],data[i+18]-data[i+2]],cross=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];if(cross[0]*data[i+3]+cross[1]*data[i+4]+cross[2]*data[i+5]<0){for(let j=0;j<8;j++){let t=data[i+8+j];data[i+8+j]=data[i+16+j];data[i+16+j]=t}}}for(const m of meshes){group.remove(m);m.geometry.dispose()}meshes=[];for(let inside=0;inside<2;inside++){let selected=[];for(let i=0;i<data.length;i+=24)if((data[i+6]>.5?1:0)===inside)selected.push(i);const p=new Float32Array(selected.length*9),n=new Float32Array(selected.length*9),uv=new Float32Array(selected.length*6),ao=new Float32Array(selected.length*3);let k=0;for(let start of selected){let us=[];for(let j=0;j<3;j++){let i=start+j*8;us.push(Math.atan2(data[i+2],data[i])/(Math.PI*2)+.5)}if(Math.max(...us)-Math.min(...us)>.5)us=us.map(x=>x<.5?x+1:x);for(let j=0;j<3;j++){let i=start+j*8;p.set(data.subarray(i,i+3),k*3);n.set(data.subarray(i+3,i+6),k*3);uv[k*2]=us[j];uv[k*2+1]=data[i+1]/2.8+.5;ao[k]=data[i+7];k++}}
 const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(p,3));g.setAttribute('normal',new T.BufferAttribute(n,3));g.setAttribute('uv',new T.BufferAttribute(uv,2));g.setAttribute('cavity',new T.BufferAttribute(ao,1));g.computeBoundingSphere();let mesh=new T.Mesh(g,inside?inner:outer);group.add(mesh);meshes.push(mesh)}}
 function render(w,h,s,highResolution=false){const rw=highResolution?Math.max(1,Math.round(w*Math.min(1,4096/Math.max(w,h)))):Math.min(1600,Math.round(w)),rh=Math.max(1,Math.round(h*rw/w));if(renderer.domElement.width!==rw||renderer.domElement.height!==rh)renderer.setSize(rw,rh,false);camera.aspect=w/h;let k=Math.min(w*.32,h*.29)*s.zoom;camera.fov=2*Math.atan(h/(10*k))*180/Math.PI;camera.updateProjectionMatrix();group.quaternion.fromArray(s.orientation).normalize();outer.color.set(s.surfaceColor);outer.roughness=s.roughness;outer.metalness=s.metalness;outer.normalScale.setScalar(s.normalStrength);for(const tex of textures)tex.repeat.set(s.textureScale,s.textureScale);overlay.value=s.displayMode==='overlay'?1:0;renderer.toneMappingExposure=s.exposure;
 const env=s.environment;if(env!=='key'&&env!==environment&&env!==loadingEnv)setEnvironment(env);const hasEnv=env!=='key'&&!!scene.environment;key.visible=fill.visible=!hasEnv;scene.environmentIntensity=hasEnv?s.envIntensity*(env==='studio'?6:3):0;scene.environmentRotation.y=s.lightAngle*Math.PI/180;key.position.set(Math.sin(s.lightAngle*Math.PI/180)*4,3,Math.cos(s.lightAngle*Math.PI/180)*4);renderer.render(scene,camera);return renderer.domElement}
 report('PBR textures ready');return {geometry,render,isReady:s=>s.environment==='key'||environment===s.environment};
}


